"""extend_schema_for_agents_and_orders

Revision ID: 5b0ede91dc5b
Revises: 8f59e280fa22
Create Date: 2026-07-16 01:55:21.839372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b0ede91dc5b'
down_revision: Union[str, Sequence[str], None] = '8f59e280fa22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('exchange_tag', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('original_order_id', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('stock_decremented', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'orders', 'orders', ['original_order_id'], ['id'])
    op.drop_index(op.f('ix_otp_sessions_lookup'), table_name='otp_sessions')
    op.drop_index(op.f('ix_product_specifications_key'), table_name='product_specifications')
    op.drop_index(op.f('ix_product_specifications_product'), table_name='product_specifications')
    op.add_column('products', sa.Column('product_images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('products', sa.Column('catalogue_images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('products', sa.Column('extraction_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('seller_corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('activation_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('returns', sa.Column('return_type', sa.String(length=16), server_default='refund', nullable=False))
    op.add_column('returns', sa.Column('status', sa.String(length=24), server_default='pending_evidence', nullable=False))
    op.add_column('returns', sa.Column('evidence_images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('returns', sa.Column('evidence_checks', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('returns', sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('returns', sa.Column('pickup_status', sa.String(length=24), nullable=True))
    op.add_column('returns', sa.Column('refund_status', sa.String(length=24), nullable=True))
    op.add_column('returns', sa.Column('refund_masked_details', sa.String(length=255), nullable=True))
    op.add_column('returns', sa.Column('replacement_order_id', sa.String(length=32), nullable=True))
    op.add_column('returns', sa.Column('status_timeline', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.create_foreign_key(None, 'returns', 'orders', ['replacement_order_id'], ['id'])
    op.add_column('reviews', sa.Column('media_hidden_by_agent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('reviews', sa.Column('awaiting_analysis', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('reviews', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('reviews', sa.Column('media_relevance_score', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_wishlist_user'), table_name='wishlist_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wishlist_user'), 'wishlist_items', ['user_id'], unique=False)
    op.drop_column('reviews', 'media_relevance_score')
    op.drop_column('reviews', 'relevance_score')
    op.drop_column('reviews', 'awaiting_analysis')
    op.drop_column('reviews', 'media_hidden_by_agent')
    op.drop_constraint(None, 'returns', type_='foreignkey')
    op.drop_column('returns', 'status_timeline')
    op.drop_column('returns', 'replacement_order_id')
    op.drop_column('returns', 'refund_masked_details')
    op.drop_column('returns', 'refund_status')
    op.drop_column('returns', 'pickup_status')
    op.drop_column('returns', 'pickup_date')
    op.drop_column('returns', 'evidence_checks')
    op.drop_column('returns', 'evidence_images')
    op.drop_column('returns', 'status')
    op.drop_column('returns', 'return_type')
    op.drop_column('products', 'activation_timestamp')
    op.drop_column('products', 'seller_corrections')
    op.drop_column('products', 'extraction_results')
    op.drop_column('products', 'catalogue_images')
    op.drop_column('products', 'product_images')
    op.create_index(op.f('ix_product_specifications_product'), 'product_specifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_specifications_key'), 'product_specifications', ['key'], unique=False)
    op.create_index(op.f('ix_otp_sessions_lookup'), 'otp_sessions', ['user_id', 'phone', 'address_session_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'stock_decremented')
    op.drop_column('orders', 'original_order_id')
    op.drop_column('orders', 'exchange_tag')
    op.drop_table('support_interactions')
    # ### end Alembic commands ###
