"""add_vishwas_samvad_and_operational_columns

Revision ID: 64b0d502aaec
Revises: 2d10c82f454f
Create Date: 2026-07-17 02:04:29.368246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64b0d502aaec'
down_revision: Union[str, Sequence[str], None] = '2d10c82f454f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('page_route', sa.String(length=255), nullable=True),
    sa.Column('page_type', sa.String(length=24), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('return_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('sender', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('addresses', sa.Column('phone_lookup_validated', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('addresses', sa.Column('lookup_status', sa.String(length=32), nullable=True))
    op.add_column('addresses', sa.Column('lookup_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('order_items', sa.Column('delivery_front_image', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('delivery_back_image', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('delivery_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('promised_delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('rescheduled_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('orders', sa.Column('whatsapp_workflow_state', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('delivery_boy_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['delivery_boy_id'], ['id'])
    op.add_column('returns', sa.Column('buyer_front_image', sa.String(length=255), nullable=True))
    op.add_column('returns', sa.Column('buyer_back_image', sa.String(length=255), nullable=True))
    op.add_column('returns', sa.Column('similarity_front', sa.Float(), nullable=True))
    op.add_column('returns', sa.Column('similarity_back', sa.Float(), nullable=True))
    op.add_column('returns', sa.Column('similarity_aggregate', sa.Float(), nullable=True))
    op.add_column('returns', sa.Column('attempt_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('returns', sa.Column('inspection_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('returns', sa.Column('delivery_boy_id', sa.String(length=32), nullable=True))
    op.add_column('returns', sa.Column('otp_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_foreign_key(None, 'returns', 'users', ['delivery_boy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'returns', type_='foreignkey')
    op.drop_column('returns', 'otp_verified')
    op.drop_column('returns', 'delivery_boy_id')
    op.drop_column('returns', 'inspection_checklist')
    op.drop_column('returns', 'attempt_history')
    op.drop_column('returns', 'similarity_aggregate')
    op.drop_column('returns', 'similarity_back')
    op.drop_column('returns', 'similarity_front')
    op.drop_column('returns', 'buyer_back_image')
    op.drop_column('returns', 'buyer_front_image')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_boy_id')
    op.drop_column('orders', 'whatsapp_workflow_state')
    op.drop_column('orders', 'rescheduled_count')
    op.drop_column('orders', 'promised_delivery_date')
    op.drop_column('order_items', 'delivery_metadata')
    op.drop_column('order_items', 'delivery_back_image')
    op.drop_column('order_items', 'delivery_front_image')
    op.drop_column('addresses', 'lookup_data')
    op.drop_column('addresses', 'lookup_status')
    op.drop_column('addresses', 'phone_lookup_validated')
    op.drop_table('chat_messages')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
