"""add review validation audit fields

Revision ID: c65ff7497d27
Revises: 64b0d502aaec
Create Date: 2026-07-17 09:54:26.482369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65ff7497d27'
down_revision: Union[str, Sequence[str], None] = '64b0d502aaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('validation_provider', sa.String(length=50), nullable=True))
    op.add_column('reviews', sa.Column('validation_model', sa.String(length=50), nullable=True))
    op.add_column('reviews', sa.Column('product_image_match_passed', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('product_image_match_confidence', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('product_image_match_reason', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('image_text_match_passed', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('image_text_match_confidence', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('image_text_match_reason', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('text_quality_passed', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('text_quality_classification', sa.String(length=50), nullable=True))
    op.add_column('reviews', sa.Column('text_quality_reason', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('overall_passed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'overall_passed')
    op.drop_column('reviews', 'text_quality_reason')
    op.drop_column('reviews', 'text_quality_classification')
    op.drop_column('reviews', 'text_quality_passed')
    op.drop_column('reviews', 'image_text_match_reason')
    op.drop_column('reviews', 'image_text_match_confidence')
    op.drop_column('reviews', 'image_text_match_passed')
    op.drop_column('reviews', 'product_image_match_reason')
    op.drop_column('reviews', 'product_image_match_confidence')
    op.drop_column('reviews', 'product_image_match_passed')
    op.drop_column('reviews', 'validation_model')
    op.drop_column('reviews', 'validation_provider')
    # ### end Alembic commands ###
