"""change reviews unique constraint to buyer_id, order_id, product_id

Revision ID: cd1bec29c627
Revises: 6a2f37d9c841
Create Date: 2026-07-20 03:21:56.704116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1bec29c627'
down_revision: Union[str, Sequence[str], None] = '6a2f37d9c841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reviews_buyer_id_product_id', 'reviews', type_='unique')
    op.create_unique_constraint('uq_reviews_buyer_id_order_id_product_id', 'reviews', ['buyer_id', 'order_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reviews_buyer_id_order_id_product_id', 'reviews', type_='unique')
    op.create_unique_constraint('uq_reviews_buyer_id_product_id', 'reviews', ['buyer_id', 'product_id'])
    # ### end Alembic commands ###
